apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: dev

resources:
- ../../base

commonLabels:
  env: dev

patches:
# Configure the Deployment for dev environment:
# - Sets single replica for dev
# - Sets lower resource limits for dev environment
- target:
    kind: Deployment
    name: joke-proxy
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "50m"

    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "256Mi"

    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "500m"

    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "256Mi"

# Configure Ingress
# - Sets the host to the proper subdomain
- target:
    kind: Ingress
    name: joke-proxy-ingress
  # Set environment hostname as the subdomain
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: "dev.joke-proxy.127.0.0.1.nip.io"

# Configure ConfigMap for dev environment:
# - Append environment suffix to DB_USER and DB_NAME
- target:
    kind: ConfigMap
    name: joke-proxy-config
  patch: |-
    - op: replace
      path: /data/DB_USER
      value: joke-user-dev
    - op: replace
      path: /data/DB_NAME
      value: joke-db-dev
