namespace: staging

resources:
- ../../base

commonLabels:
  env: staging

patches:
# Configure the Deployment for staging environment:
# - Sets 2 replicas for staging
# - Sets medium resource limits for staging environment
- target:
    kind: Deployment
    name: joke-proxy
  patch: |-
    - op: replace
      path: /spec/replicas
      value: 2

    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/cpu
      value: "200m"

    - op: replace
      path: /spec/template/spec/containers/0/resources/requests/memory
      value: "256Mi"

    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/cpu
      value: "400m"

    - op: replace
      path: /spec/template/spec/containers/0/resources/limits/memory
      value: "512Mi"

# Configure Ingress
# - Sets the host to the proper subdomain
- target:
    kind: Ingress
    name: joke-proxy-ingress
  # Set environment hostname as the subdomain
  patch: |-
    - op: replace
      path: /spec/rules/0/host
      value: "staging.joke-proxy.127.0.0.1.nip.io"

# Configure ConfigMap for staging environment:
# - Append environment suffix to DB_USER and DB_NAME
- target:
    kind: ConfigMap
    name: joke-proxy-config
  patch: |-
    - op: replace
      path: /data/DB_USER
      value: joke-user-staging
    - op: replace
      path: /data/DB_NAME
      value: joke-db-staging
