version: '3.8'

services:
  app:
    build: .
    container_name: joke-proxy
    image: joke-proxy:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    volumes:
      - .:/app

  mongo:
    image: mongo:8.0.4
    container_name: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=jokesDB
    volumes:
      - mongo_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

volumes:
  mongo_data:
